### ISSUE TITLE
pem私钥都上传了

### ISSUE THREAD

**Issue by dh360** [Zhang19910325/nodejs-server-wechat-landLordGame#1]

**Comment by Zhang19910325** [comment]
测试时用的自签证书，自己服务器的正式证书没有上传

**Comment by dh360** [comment]
好的， 公司让做斗地主的游戏， 像你学习一下

**Comment by Zhang19910325** [comment]
这里包含客户端、服务器；基本上可以简单的玩了，只不过我没有用引擎，也可以说我自己写了个简单的小引擎，不懂的话可以提。现在想把炸金花也做进去，等会会把真机运行的界面放上来，因为有些变动了。

**Comment by dh360** [comment]
@Zhang19910325 好的
